version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./logs:/var/log/nginx
      - shared-public:/var/www/html/public    # ✅ accede al volumen compartido
    networks:
      - proxy_net
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true

volumes:
  shared-public:
    external: true
    name: shared-public   # ✅ igual que en Laravel
