version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - ./conf.d:/etc/nginx/conf.d                     # Archivos de configuración Nginx
      - ./certbot/www:/var/www/certbot                 # Webroot para desafío HTTP de Certbot
      - ./certbot/conf:/etc/letsencrypt                # Certificados reales emitidos por Let's Encrypt
      - ./logs:/var/log/nginx                          # Logs Nginx
    networks:
      - proxy_net
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
